### ISSUE TITLE
My question is, is there a command I can execute to force payments? 

### ISSUE THREAD

**Issue by ICOBOXER** [valiant1x/intense-pool#2]
Pool has delivered payments with no problems, however, after upgrade I notice that that my wallet (mi mining wallet) still have a pending balance, very large for the default minimum. 

Pending Balance: 836.62126179 ITNS  

Check out this wallet payment history at http://intense.miningpools.us/
iz5MjphBKgrfFmujDTd33W7rTc3MFNYYuUxcduBuZEqJKQ6NbZHHga2gvSAh1W4FugR6jD8Rktva2L9kpMry2MZS16DxaoBJZ

My question is, is there a command I can execute to force payments?

**Comment by valiant1x** [comment]
There is no command to force payments. You can reduce the delay on the payment interval if that suits your needs.
